### ISSUE TITLE
Wrong version number in minified 5.3.0

### ISSUE THREAD

**Issue by MHLut** [tristen/tablesort#216]
See [minified version 5.3.0 on unpkg](https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js), comment header on top of the file. The comment on top of the file lists the version as `5.2.1` instead of `5.3.0`.

I've checked [minified version 5.2.1 on unpkg](https://unpkg.com/tablesort@5.2.1/dist/tablesort.min.js), which has different file contents, which leads me to believe that the `5.3.0` has the wrong version comment on top of the file.

Related commit: https://github.com/tristen/tablesort/commit/4fec8c3c383d61735764ca194d4fb00043456312

**Comment by tripu** [comment]
(Not about [Unpkg](https://unpkg.com/) specifically; the release `5.3.0` is [wrong here on GH](https://github.com/tristen/tablesort/compare/5.2.1...5.3.0), too.)

I see. For some reason, 4fec8c3c383d61735764ca194d4fb00043456312 did not set the right version in the headers of all the files under `dist/`. It's weird, because the _date_ was set correctly, and also because I just ran `npm run build` on my local environment, and Grunt interpolated and updated those strings as expected (the version, too).

I was tempted to open a PR to fix this, but if we merge that, either we will bump the version just for this mostly irrelevant change, or we republish the _same_ version to fix those comments&hellip; both options seem wrong to me. I think we can live with the misleading comment blocks until a new version is released. **So I would close this.**

Thoughts from the other maintainers?
